// importing from byungyoonc - need to customize
#define MOUSEKEY_DELAY 2
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_MOVE_DELTA 3
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_WHEEL_DELAY 2
#define MOUSEKEY_WHEEL_INTERVAL 40

#define MK_COMBINED

#define MASTER_RIGHT

#define TAPPING_TERM 150
#define HOLD_ON_OTHER_KEY_PRESS
#define QUICK_TAP_TERM 0

// #define USB_MAX_POWER_CONSUMPTION 100
