#pragma once

#ifndef KEYBOARD_preonic_rev3
fuck this shit imma out;
#endif

#ifndef CONSOLE_ENABLE

#ifndef NO_DEBUG
#define NO_DEBUG
#endif

#ifndef NO_PRINT
#define NO_PRINT
#endif

#else

#define DEBUG_MATRIX_SCAN_RATE

#endif

#define NO_MUSIC_MODE
#ifdef AUDIO_CLICKY
#undef AUDIO_CLICKY
#endif

#ifdef AUTO_SHIFT_MODIFIERS
#undef
#endif

#define TAPPING_TERM 150
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#ifdef RETRO_TAPPING
#undef RETRO_TAPPING
#endif

#define ONESHOT_TIMEOUT 5000

#ifdef RGBLIGHT_ANIMATIONS
#undef RGBLIGHT_ANIMATIONS
#endif

// #define RGB_MATRIX_ENABLE
#define RGBLIGHT_LAYERS
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGBLIGHT_SLEEP

#define RGBLIGHT_DEFAULT_HUE 0
#define RGBLIGHT_DEFAULT_SAT 0
#define RGBLIGHT_DEFAULT_VAL 0

#define MK_COMBINED

#define MOUSEKEY_DELAY 60
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 8

#define MOUSEKEY_WHEEL_MAX_SPEED 10
#define MOUSEKEY_WHEEL_TIME_TO_MAX 45
#define MOUSEKEY_WHEEL_DELAY 60
#define MOUSEKEY_WHEEL_INTERVAL 100

#define USB_POLLING_INTERVAL_MS 1

#define USB_MAX_POWER_CONSUMPTION 100

#define FORCE_NKRO
