kime_version: '^4.0.0-pre.1'

daemon:
  modules:
  - Wayland
  - Indicator

indicator:
  icon_color: White

engine:
  default_category: Latin
  global_category_state: true
  global_hotkeys:
    Hangul:
      behavior:
        Toggle:
        - Hangul
        - Latin
      result: Consume
    AltR:
      behavior:
        Toggle:
        - Hangul
        - Latin
      result: Consume
    Esc:
      behavior:
        Switch: Latin
      result: Bypass
    S-Hangul:
      behavior:
        Mode: Emoji
      result: ConsumeIfProcessed

    # # other modes don't work
    # C-Hangul:
    #   behavior: !Mode Hanja
    #   result: ConsumeIfProcessed
    # M-Hangul:
    #   behavior: !Mode Math
    #   result: ConsumeIfProcessed

  mode_hotkeys:
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      # Tab:
      #   behavior: Commit
      #   result: ConsumeIfProcessed
    # Hanja: *commit
    # Math: *commit

  latin:
    preferred_direct: true

  hangul:
    layout: xnuk
    word_commit: false
    addons:
      xnuk:
      - ComposeChoseongSsang
      - ComposeJongseongSsang
      - ComposeJungseongSsang
