daemon:
  modules: []
engine:
  default_category: Latin
  global_category_state: true
  global_hotkeys:
    Hangul:
      behavior:
        Toggle:
        - Hangul
        - Latin
      result: Consume
    S-Space:
      behavior:
        Switch: Hangul
      result: ConsumeIfProcessed
    Esc:
      behavior:
        Switch: Latin
      result: Bypass
  category_hotkeys: {}
  mode_hotkeys: {}
  latin:
    preferred_direct: true

  hangul:
    layout: xnuk
    word_commit: false
    addons:
      xnuk:
      - ComposeChoseongSsang
      - ComposeJongseongSsang
      - ComposeJungseongSsang

