daemon:
  modules:
  - Wayland
  - Indicator

indicator:
  icon_color: White

engine:
  default_category: Latin
  global_category_state: true
  global_hotkeys:
    Hangul: &toggle
      behavior: !Toggle [Hangul, Latin]
      result: Consume
    AltR: *toggle
    Esc:
      behavior: !Switch Latin
      result: Bypass

  latin:
    preferred_direct: true

  hangul:
    layout: xnuk
    word_commit: false
    addons:
      xnuk:
      - ComposeChoseongSsang
      - ComposeJongseongSsang
      - ComposeJungseongSsang
