SRC += muse.c
NKRO_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = yes

DIP_SWITCH_ENABLE = no
LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
AUTO_SHIFT_ENABLE = no
KEY_LOCK_ENABLE = no
POINTING_DEVICE_ENABLE = no
