# vim: sw=2

name: preonic-build

on:
  workflow_dispatch: {}
  push:
    branches:
    - preonic
    paths:
    - '*.c'
    - '*.h'
    - '*.mk'
    - .github/workflows/build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/base_container

    steps:
    - run: ls $QMK_HOME

    - uses: actions/checkout@v2
      with:
        ref: e0614e4f52875f337668e9530ab3dcf7ce74c8cc
        repository: qmk/qmk_firmware
        submodules: recursive
        path: ''

    - uses: actions/checkout@v2
      with:
        path: keyboards/preonic/keymaps/xnuk

    - run: pip3 install --user -r requirements.txt
    - run: bin/qmk compile -kb preonic/rev3 -km xnuk

    - uses: actions/upload-artifact@v2
      with:
        name: preonic_rev3_xnuk
        path: .build/preonic_rev3_xnuk.{bin,hex}
