# vim: sw=2
name: preonic-build

on:
  workflow_dispatch: {}
  push:
    branches:
    - preonic
    paths:
    - '*.c'
    - '*.h'
    - '*.mk'
    - .github/workflows/qmk-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    # Made an issue for pinning this stuff
    # https://github.com/qmk/qmk_cli/issues/173
    container: ghcr.io/qmk/qmk_cli

    steps:
    - uses: actions/checkout@v4
      with:
        ref: c5f544cd9696eb607e88b921d3fc31959ada914a
        repository: qmk/qmk_firmware
        submodules: recursive
        path: ''

    - uses: actions/checkout@v4
      with:
        path: keyboards/preonic/keymaps/xnuk

    - run: pip3 install --user -r requirements.txt
    - run: make preonic/rev3:xnuk

    - uses: actions/upload-artifact@v4
      with:
        name: preonic_rev3_xnuk
        path: |
          preonic_rev3_xnuk.*
          .**/preonic_rev3_xnuk.*
          **/preonic_rev3_xnuk.*
