# vim: sw=2
name: preonic-build

on:
  workflow_dispatch: {}
  push:
    branches:
    - preonic
    paths:
    - '*.c'
    - '*.h'
    - '*.mk'
    - .github/workflows/build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 80708c64a1b258f39346083cfb81b930a501499c
        repository: qmk/qmk_firmware
        submodules: recursive
        path: ''

    - uses: actions/checkout@v2
      with:
        path: keyboards/preonic/keymaps/xnuk

    - run: pip3 install --user -r requirements.txt
    - run: qmk compile -kb preonic/rev3 -km xnuk

    - uses: actions/upload-artifact@v2
      with:
        name: preonic_rev3_xnuk
        path: |
          preonic_rev3_xnuk.*
          .**/preonic_rev3_xnuk.*
          **/preonic_rev3_xnuk.*
